language: objective-c
osx_image: xcode7.0
sudo: false

before_install:
    - rvm get head
    - alias brew=echo
    - alias npm=echo
    - alias cp=echo
    - brew update
    - brew unlink node
    - brew install node@4
    - brew link node --force
    - brew install --ignore-dependencies wine
    - brew install github-release
    - brew install mono
    - brew install fakeroot
    - brew install dpkg
    - brew install coveralls
    - npm install
    - npm update
    
script:
    - "npm -gp outdated | cut -d: -f4 | xargs -n1 npm -g install"
    - cd node_modules
    - npm test
    - npm run integration

after_success:
    - coveralls --rcfile=.coveragerc
    - npm run release
